sample_sheet: "config/sample_sheet.tsv"

filtering:
  # Median absolute deviation (MAD) of three counts quality control values,
  # above which a cell is considered an outlier. For details, see:
  # https://www.sc-best-practices.org/preprocessing_visualization/quality_control.html#filtering-low-quality-cells
  counts_mads: 5
  # Mitochondrial counts percentage from all counts, above which a cell is
  # considered an outlier. For details, see:
  # https://www.sc-best-practices.org/preprocessing_visualization/quality_control.html#filtering-low-quality-cells
  mt_percent: 20
  # Median absolute deviation (MAD) of mitochondrial counts percentage from all
  # counts, above which a cell is considered an outlier. For details, see:
  # https://www.sc-best-practices.org/preprocessing_visualization/quality_control.html#filtering-low-quality-cells
  mt_percent_mads: 5