$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  sample_sheet:
    type: string
    description: path to sample sheet, mandatory
    default: config/sample_sheet.tsv

  filtering:
    type: object
    properties:
      counts_mads:
        type: integer
        description: Median absolute deviation (MAD) of three counts quality control values, above which a cell is considered an outlier.
        default: 5
      mt_percent:
        type: integer
        description: Mitochondrial counts percentage from all counts, above which a cell is considered an outlier.
        default: 20
      mt_percent:
        type: integer
        description: Median absolute deviation (MAD) of mitochondrial counts percentage from all counts, above which a cell is considered an outlier.
        default: 5
    required:
      - counts_mads
      - mt_percent
      - mt_percent_mads

required:
  - sample_sheet
  - filtering
